### ISSUE TITLE
El backend no establece cookies cuando responde a peticiones del frontend (deploy)

### ISSUE THREAD

**Issue by Araozu** [digitales-2024/api-chaqchao#158]
https://develop-chaqchao-admin.acide.win/  -- frontend admin
https://develop-chaqchao-api.acide.win/  -- backend

Cuando el frontend inicia sesión, el backend responde correctamente y CORS funciona, pero no se establecen las cookies de sesión.

## Pasos para reproducir

- Ir a https://develop-chaqchao-admin.acide.win/  (ya está seedeado)
- Iniciar sesion con el usuario admin
  ![image](https://github.com/user-attachments/assets/c1743ac2-b2f7-4e1f-96c2-76e7a93dcead)
- El backend responde con 201 OK
  ![image](https://github.com/user-attachments/assets/5dc64f90-96eb-4532-8a77-89851dc9e797)
- El backend responde correctamente con las cookies de JWT y JWT_REFRESH
  ![image](https://github.com/user-attachments/assets/9f475873-79d4-412f-8c12-539a7d337677)
- Sin embargo, la página no se actualiza. Esto se debe a que las cookies no se almacenan:
  ![image](https://github.com/user-attachments/assets/4eb1c815-6e24-47ba-bf85-080cdf896764)

Esto se debe a que, por defecto, no se pueden enviar cookies entre dominios diferentes:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials

## Soluciones

- ~~Establecer el header de CORS [Access-Control-Allow-Credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials) a true~~ ver comentario abajo

**Comment by Araozu** [comment]
Trazo tuvo el mismo problema al deployar y se solucionó agregando `domain` a todos los lugares del backend donde se manejan cookies:

En `auth/auth.service.ts`:
```typescript
      // Configura la cookie HttpOnly
      res.cookie('access_token', token, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'strict',
        path: '/',
        maxAge: this.configService.get('COOKIE_EXPIRES_IN'),
        //
        // se agregó esto
        //
        domain: process.env.WEB_DOMAIN,
        expires: new Date(
          Date.now() + this.configService.get('COOKIE_EXPIRES_IN'),
        ),
      });
```

Se agregó `domain: process.env.WEB_DOMAIN` a todas las cookies, y esto solucionó el problema en trazo. Al momento de deployar se configurará esta variable de entorno.

## Por qué sucede este error

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent)

Cuando el backend y frontend están en subdominios diferentes (ejm `api.trazo.com` y `admin.trazo.com`), y el backend envía cookies sin el campo `Domain` se sobreentiende que las cookies son exclusivas del subdominio del backend `api.trazo.com`. Se puede establecer `Domain` para que estas cookies se puedan utilizar en otros subdominios. Por ejemplo, establecer `Domain=admin.trazo.com` hace que las cookies se puedan utilizar en el frontend. Esto solo funciona cuando back y front estan en el mismo dominio, pero diferentes subdominios.

**Comment by AcideTI** [comment]
Se agregó `process.env.WEB_DOMAIN` para la tienda y `process.env.ADMIN_DOMAIN`
